name: pyPIPS_test
channels:
  - conda-forge
dependencies:
  - arm_pyart
  - autopep8
  - beautifulsoup4
  - bottleneck
  - cartopy
  - cftime
  - dask
  - flake8
  - gfortran
  - h5py
  - h5netcdf
  - ipykernel
  - joblib
  - lxml
  - matplotlib
  - metpy
  - nbdime
  - netcdf4
  - numba
  - numpy
  - pandas
  - pip
  - pylint
  - pytz
  - python
  - scipy
  - urllib3
  - xarray
  - pip:
    - "--editable=git+https://github.itap.purdue.edu/STorMLab/pyCRMtools.git@master#egg=pyCRMtools"
