name: pyPIPS
channels:
  - conda-forge
dependencies:
  - arm_pyart
  - autopep8
  - basemap
  - basemap-data-hires
  - beautifulsoup4
  - cartopy
  - cftime
  - flake8
  - joblib
  - jupyter
  - matplotlib
  - metpy
  - nbdime
  - netcdf4
  - numba
  - numpy
  - pandas
  - pip
  - pylint
  - pynio
  - pytz
  - scipy
  - urllib3
  - xarray
  - pip:
    - "--editable=git+https://github.rcac.purdue.edu/STorMLab/pyCRMtools.git@master#egg=pyCRMtools"

